name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        postgres: [14]
    steps:
    - uses: actions/checkout@v2

    # install postgres
    - run: C:\msys64\usr\bin\pacman --noconfirm -S mingw-w64-x86_64-postgresql gettext-devel
    - run: echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - run: pg_config
    - run: initdb -D data -U postgres

    # install pgvector
    - run: make PG_CFLAGS="-IC:/msys64/usr/include"
    - run: make install

    # run tests
    - run: pg_ctl -D data start
    - run: mkdir /tmp
    - run: make installcheck
    - if: ${{ failure() }}
      run: cat regression.diffs
